[package]
name = "canvas-native"
version = "1.0.0"
authors = ["Osei Fortune <fortune.osei@yahoo.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "canvasnative"
crate-type = ["staticlib", "cdylib"]


[build]
rustc-wrapper = "sccache"

[build-dependencies]
bindgen = "0.57.0"
cmake = "0.1.44"
cc = "1.0.73"
cbindgen = "0.20.0"

[dependencies]
regex = "1.5.4"
base64 = "0.13.0"
image = "0.23.7"
encoding_rs = "0.8.24"
gl-bindings = { version = "0.1.0", path = "../gl-bindings" }
lazy_static = "1.4.0"
css-color-parser = "0.1.2"
phf = { version = "0.10.1", features = ["macros"] }
rgb = "0.8.25"
log = "0.4.8"
stringreader = "0.1.1"
rand = "0.8.4"
once_cell = "1.8.0"

[target.'cfg(target_os="android")'.dependencies]
openssl = { version = "0.10.38", features = ["vendored"]}
jni = { version = "0.19.0", default-features = false }
android_logger = "0.9.0"
parking_lot = "0.12.0"
#skia-safe = { git = "https://github.com/triniwiz/rust-skia", branch="feat/svg" , features = ["gl"] }
#skia-safe = { version = "0.43.0", features = ["gl"] }
skia-safe = { path = "/Users/triniwiz/desktop/oss/rust-skia/skia-safe", features = ["gl", "svg"] }

[target.'cfg(target_os="ios")'.dependencies]
#skia-safe = { version = "0.43.0", features = ["gl"] }
#skia-safe = { git = "https://github.com/triniwiz/rust-skia", branch="feat/svg" , features = ["gl"] }
skia-safe = { path = "/Users/triniwiz/desktop/oss/rust-skia/skia-safe", features = ["gl", "svg"] }
cocoa = { version = "0.24.0" }
objc = { version = "0.2.4" }
block = "0.1.6"



