[package]
name = "canvas-core"
version = "1.0.0"
authors = ["Osei Fortune <fortune.osei@yahoo.com>"]
edition = "2021"

[features]
metal = ["skia-safe/metal"]
gl = ["skia-safe/gl"]

[dependencies]
parking_lot = "0.12.0"
regex = "1.5.4"
base64 = "0.13.0"
image = "0.23.7"
encoding_rs = "0.8.24"
gl-bindings = { version = "0.1.0", path = "../gl-bindings" }
lazy_static = "1.4.0"
css-color-parser = "0.1.2"
phf = { version = "0.10.1", features = ["macros"] }
rgb = { version = "0.8.32", features = ["argb"] }
log = "0.4.8"
stringreader = "0.1.1"
rand = "0.8.4"
once_cell = "1.8.0"
skia-bindings = { git = "https://github.com/triniwiz/rust-skia.git", rev = "d60f2c94", features = ["gl"] }
skia-safe = { git = "https://github.com/triniwiz/rust-skia.git", rev = "d60f2c94", features = ["gl"] }
stb = { git = "https://github.com/triniwiz/stb.git", rev = "d197a1b", features = ["stb_image", "stb_image_write", "stb_image_resize"] }
stb-sys = { git = "https://github.com/triniwiz/stb.git", rev = "d197a1b", features = ["stb_image", "stb_image_write", "stb_image_resize"] }



