[package]
name = "canvas-android-v8"
version = "0.1.0"
edition = "2021"


[lib]
name = "canvasnativev8"
crate-type = ["cdylib"]

[build-dependencies]
cxx-build = "1.0.66"
bindgen = "0.59.2"

[dependencies]
canvas-core = { path = "../canvas-core" , features = ["gl"]}
gl-bindings = { path = "../gl-bindings" }
cxx = "1.0.66"
ureq = "2.4.0"
image = "0.23.7"
parking_lot = "0.12.0"
egl = "0.2.7"
jni = "0.19.0"
libc = "0.2.121"
once_cell = "1.10.0"

[target.'cfg(target_os="android")'.dependencies]
openssl = {version = "0.10.38", features = ["vendored"]}
