[package]
name = "canvas-android-v8"
version = "0.1.0"
edition = "2021"


[lib]
name = "canvasnativev8"
crate-type = ["cdylib"]

[build-dependencies]
cxx-build = "1.0"
bindgen = "0.59.2"

[dependencies]
canvas-core = { path = "../canvas-core" , features = ["gl"]}
cxx = "1.0"
ureq = "2.4.0"
image = "0.23.7"
parking_lot = "0.12.0"
egl = "0.2.7"
jni = "0.19.0"
libc = "0.2.121"

