[package]
name = "canvas-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "canvasnative"
crate-type = ["cdylib"]

[features]
default = ["gl"]
gl = ["canvas-core/gl"]

[build]
rustc-wrapper = "sccache"

[build-dependencies]
bindgen = "0.57.0"
cmake = "0.1.44"
cc = "1.0.73"


[dependencies]
gl-bindings = { path = "../gl-bindings" }
canvas-core = { path = "../canvas-core" }
once_cell = "1.8.0"
openssl = { version = "0.10.38", features = ["vendored"] }
jni = { version = "0.19.0", default-features = false }
android_logger = "0.9.0"
parking_lot = "0.12.0"
skia-bindings = { path = "../../rust-skia/skia-bindings", features = ["gl"] }
skia-safe = { path = "../../rust-skia/skia-safe", features = ["gl"] }
rgb = {version = "0.8.32", features = ["argb"]}
log = "0.4.8"
css-color-parser = "0.1.2"

