[package]
name = "v8-bindings"
version = "0.1.0"
authors = ["triniwiz <fortune.osei@yahoo.com>"]
edition = "2018"
build = "build.rs"

[build]
rustc-wrapper = "sccache"

[build-dependencies]
bindgen = "0.58.1"
cmake = "0.1.44"
cc = "1.0.56"


[dependencies]
