cargo-features=["strip"]

[workspace]

members = [
    "gl-bindings",
    "canvas-core"
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
#opt-level = 3
opt-level = "z"
debug = false
incremental = false
strip = "symbols"
