[workspace]

members = [
    "gl-bindings",
    "canvas-core",
    "canvas-android",
    "canvas-ios",
    "canvas-ffi",
    "canvas-android-v8"
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
debug = false
incremental = false
strip = true
