[package]
name = "canvas-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "canvasffi"
crate-type = ["staticlib"]

[features]
gl = ["canvas-core/gl"]

[build]
rustc-wrapper = "sccache"

[build-dependencies]
bindgen = "0.57.0"
cmake = "0.1.44"
cc = "1.0.73"
cbindgen = "0.20.0"

[dependencies]
gl-bindings = { path = "../gl-bindings" }
canvas-core = { path = "../canvas-core" }
skia-bindings = { path = "../../rust-skia/skia-bindings", features = ["gl"] }
skia-safe = { path = "../../rust-skia/skia-safe", features = ["gl"] }
image = "0.23.7"
css-color-parser = "0.1.2"